package com.example.mynews.utils

const val TOPSTORIES = "TOP STORIES"
const val MOSTPOPULAR = "MOST POPULAR"
const val BUSINESS = "BUSINESS"
const val TABTITLE = "tabTitle"
const val URL = "URL"
const val API_KEY = "FMseo3eiA9BHRp36xJY5YKvqoXantmKk"
const val QUERY="query"
const val FQ = "fq"
const val END_DATE="end_date"
const val BEGIN_DATE="begin_date"
const val TITLE = "title"
const val BASE_URL = "https://static01.nyt.com/"
const val NEWS="news"
const val NOTIF="notif"
const val DYNAMIC_LINK_DOMAIN = "https://mynewsapp.page.link"
const val DEFAULT_IMAGE_LINK  = "https://ilove.ebpl.org/sites/default/files/the-new-york-times-logo-featured.jpg"
const val IMG_LINK = "IMG_LINK"
const val ACTION = "com.example.mynews.UploadImageFirebaseService"
const val ARTICLES = "articles"