package com.example.mynews.utils

const val TOPSTORIES = "TOP STORIES"
const val MOSTPOPULAR = "MOST POPULAR"
const val BUSINESS = "BUSINESS"
const val TABTITLE = "tabTitle"
const val URL = "URL"
const val API_KEY = "FMseo3eiA9BHRp36xJY5YKvqoXantmKk"
const val QUERY="query"
const val FQ = "fq"
const val END_DATE="end_date"
const val BEGIN_DATE="begin_date"
const val TITLE = "title"
const val BASE_URL = "https://static01.nyt.com/"
const val NEWS="news"